### ISSUE TITLE
Missing properties when multiple properties use the same ref

### ISSUE THREAD

**Issue by adam1658** [wol-soft/php-json-schema-model-generator#25]
**Describe the bug**
When using a schema that has two keys that both reference the same definition in their values, only the first gets generated.

**Expected behavior**
Both properties exist in the generated PHP.
In the generated `Test.php` a search for the word `personA` returns 40 results, but a search for the word `personB` only returns 1.

**Schema**
```json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "Test",

  "definitions": {
    "person": {
      "type": "object",
      "properties": {
        "id": { "type": "string" }
      },
      "required": ["id"],
      "additionalProperties": false
    }
  },

  "type": "object",
  "properties": {
    "personA": { "$ref": "#/definitions/person" },
    "personB": { "$ref": "#/definitions/person" }
  },
  "required": ["personA", "personB"],
  "additionalProperties": false
}
```

With GeneratorConfiguration:
```php
$generator = new ModelGenerator((new GeneratorConfiguration())
    ->setNamespacePrefix('Demo')
    ->setSerialization(true)
    ->setImmutable(false)
);
```

**Version:**
0.19.0

**Additional context**
This is not my real schema, this is a minimal reproduction. The environment I did this in only has the following files:
- composer.json
- json-schema/test.json
- codegen.php

**Comment by wol-soft** [comment]
Hi @adam1658 

thanks for the report. I can reproduce the issue and will have a look into it.

Cheers

**Comment by wol-soft** [comment]
I've implemented a fix in MR #26 together with some internal refactorings of the reference resolving to avoid similar problems in the future. I'll add some test cases to the MR and then merge it.

**Comment by wol-soft** [comment]
I've tagged version 0.19.1 which includes the fix for the provided schema as well as test cases covering the issue.

**Comment by adam1658** [comment]
Thanks @wol-soft, it works great!
