### ISSUE TITLE
Integer property with default 0 is incorrectly nullable

### ISSUE THREAD

**Issue by dktapps** [wol-soft/php-json-schema-model-generator#43]
**Describe the bug**
A property with a default value is not typically nullable, but if its `default` is 0, it's marked as nullable anyway.

**Expected behavior**
Integer properties with 0 as the default value shouldn't be nullable.

**Schema**
```
				"global-limit": {
					"type": "integer",
					"minimum": 0,
					"description": "Global soft memory limit (MB). When reached, low-memory triggers will fire to try and free memory.",
					"default": 1
				},
```

**Version:**
Which version of the library do you use?
dev-master as of about 1h ago.

**Additional context**
My bet is that there's some weak comparison `==` somewhere that's responsible for this bug.

**Comment by wol-soft** [comment]
I've tagged a new bugfix version (0.21.1) which includes the fixes for the issues you opened. Thanks for the reports again!

I hope the library is useful for you, would be glad to hear how it's going 😃
