### ISSUE TITLE
uuid string type support

### ISSUE THREAD

**Issue by myalban** [wol-soft/php-json-schema-model-generator#54]
Hi,
Do you know if it's possible to support additional  format type as UUID ?

I got this error when I try to use it :

PHP Fatal error:  Uncaught PHPModelGenerator\Exception\SchemaException: Unsupported format uuid for property UUID in file openApi.json in vendor/wol-soft/php-json-schema-model-generator/src/PropertyProcessor/Property/StringProcessor.php:136

My schema is 
`
"properties": {
                    "UUID": {
                        "type": "string",
                        "minLength": 1,
                        "format": "uuid",
                    }
`
best regards,
Alban

**Comment by wol-soft** [comment]
Hi @myalban,

have you found the solution for your problem? It's possible to add custom formats to the generator (https://php-json-schema-model-generator.readthedocs.io/en/latest/types/string.html#builtin-formats) or add it as a built in format so everyone can use it.

Cheers
