### ISSUE TITLE
Support number property key

### ISSUE THREAD

**Issue by giann** [wol-soft/php-json-schema-model-generator#58]
Unfortunately some of the data we had to describe in our Json Schema are objects with number as keys like so:

```json
"Markets": {
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "2201": {
      "type": "string"
    },
    "2202": {
      "type": "string"
    },
    "2203": {
      "type": "string"
    },
    "2204": {
      "type": "string"
    },
  }
}
```

Could it be possible to support this?

**Comment by wol-soft** [comment]
Hi, yes, this should be possible. I'll have a look into it tomorrow.

**Comment by wol-soft** [comment]
@giann I've added a quick implementation draft (without further tests yet) in PR #59 (branch `dev-supportNumericProperties`). You may use the branch and look if it fixes the problem. I'll add tests tomorrow and add an entry in the documentation.

**Comment by wol-soft** [comment]
Hi @giann, I've published a new version including the fix for numeric properties and properties with leading numbers: https://github.com/wol-soft/php-json-schema-model-generator/releases/tag/0.22.1
